### ISSUE TITLE
plugins.ngdesktopfile.writeTXTFileSync with "encoding" does not work

### ISSUE THREAD

**Issue by philippr71** [Servoy/ngdesktopfile#5]
Hi 

The "plugins.ngdesktopfile.writeTXTFileSync" has an optional 3rd argument "encoding". By default this is "utf8". But it seems to be that only "utf8" works. In every other cases the file could not be written anymore (the methode returns "false").

I've tried the following:

- "windows-1252"
- "Cp1252"
- "cp1252"
- "cp-1252"
- "CP 1252"

We need to produce files with the Windows-1252 encoding:
var result = plugins.ngdesktopfile.writeTXTFileSync(destinationFilePath, "test", "windows-1252");

By the way: the methode "writeTXTFileSync" isn't documented in the wiki at all.

Thanks.
Roland

**Comment by jcompagner** [comment]
we are just mapping that on nodejs filesystem api, and that list of encodings is very small:

https://stackoverflow.com/a/14551669/5186090

so i think the only option for you is "latin1"

**Comment by philippr71** [comment]
Hi Johan
This seems to be good enough for the moment!
Another workaround would be to use the "plugins.file.writeTXTFile(myFile, "test", "windows-1252") to create a temporary file on the server, read this file (with var data = plugins.file.readFile(file)) and use the plugins.ngdesktopfile.writefile(..., data); to store the file in the right encoding on the client.
Thanks!
Best, Roland
